### ISSUE TITLE
Error in questionnaire - Forsvaret will pay for patch

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-mod_questionnaire#1]
@neeesn commented on [Thu Nov 24 2022](https://github.com/praxisdigital/moodle-opgaver/issues/211)

The Questionnair plugin sends email to users who is not enrolled in the course, via the tab "Non-respondents".
The teacher has to choose to send, but there are many useres that are not enrolled  - they are anonym 

![image.png](https://images.zenhubusercontent.com/61f3b1064ed5f55493376dfb/02fb2fe6-2091-4bdf-9dfb-54a8451a78ca)

In the screendump, there are 13 enrolled but there are 194 that will get the mail. 

Forsvaret have had a few incidences and it is not good. 

They are using version 3.10.1  and the newst version doesnt fix the problem either. 
There is a patch in this forum  https://moodle.org/mod/forum/discuss.php?d=275297 I have seen in the code of the plugin that it might have to implimentet on line 578 in the locallib.php file

If the fix can be implementet within a few hours we should just do it - else we need a quick estimate. 

_Hej Praxis,

Plugin "mod_questionnaire" (Spørgeskema) sender e-mails til brugere der ikke er tilmeldt kurset via fanebladet "Non-respondents" (Ikke-respondenter". Læreren skal godt nok selv vælge at sende via fanebladet, men den henter adskillige brugere ind, som ikke er tilmeldt (de optræder anonymt).
Nu har vi haft et par tilfælde, hvor det er sket og det er ikke så heldigt. 
I vedhæftede skærmdump er der tilmeldt 13 deltagere, men den henter 194 brugere som Ikke-respondenter.
Vi anvender build 3.10.1, sidste nye version er 3.11.1. Vi er dog ikke sikre på, at den nyeste version er rettet, da vi har fundet en gammel sag i et forum, hvor der er lavet et patch der retter den fejl. I kan læse sagen her, hvor også denne patch kan downloades: https://moodle.org/mod/forum/discuss.php?d=275297
Link til dette plugin på Moodle.org: https://moodle.org/plugins/mod_questionnaire
Kan i kigge på sagen hurtigst muligt?
På forhånd tak.
Allan_

https://praxisdigital.zendesk.com/agent/tickets/41321

---

@mcardle commented on [Thu Nov 24 2022](https://github.com/praxisdigital/moodle-opgaver/issues/211#issuecomment-1326392661)

As a part of this issue, please sync the fork in out repo, create a new version of the forked one. Apply the patch provided and create another version in Morris, called patched. Add the link to the patch under Notes in Morris. This issue should also be transferred to the forked version instead of Moodle-opgaver.

**Comment by frederikmillingpytlick** [comment]
Patch made on MOODLE_310_STABLE, MOODLE_311_STABLE and master

https://morris.praxis.dk/plugin/524

**Comment by mcardle** [comment]
@frederikmillingpytlick you need to register how much time you have spent on this issue.

**Comment by frederikmillingpytlick** [comment]
I've already added my time spent on the zendesk ticket. I spent 30 minutes
