### ISSUE TITLE
DBU - Questionnair

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-mod_questionnaire#2]
Error DBU 
https://elearning.dbu.dk/mod/questionnaire/report.php?instance=284&action=vall
![image.png](https://images.zenhubusercontent.com/61f3b1064ed5f55493376dfb/1dab6463-c404-4f35-b8aa-861d0d49488d)

Zendesk: https://praxisdigital.zendesk.com/agent/dashboard

**Comment by sampraxis** [comment]
Time spent: 3h 30m

**Comment by sampraxis** [comment]
Time spent: 3h 30m
